### ISSUE TITLE
Set of data to be deposited to Zenodo for a given submission

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#459]
For PlantPopulation submissions the following records are going to be uploaded to Zenodo:

- the submitted plant population
- female/male parent line, if present
- plant lines related to the plant population through the plant population list table
- plant varieties related to all exported plant lines

For PlantTrial submission:

- the submitted plant trial
- all (both new and old) trait descriptors used in the submission
- all plant scoring units and trait scores recorded during the submission
- all related plant accessions.

Currently the plan is to store them in separate CSV files (one per DB table) and send them in a single Zenodo deposition.

Is this data set correct?

**Comment by teatree1212** [comment]
Plant population submission content looks correct.
PlantTrial submission would probably need modification based on the minimum requirements I added in #488

**Comment by Nuanda** [comment]
Right.

**Comment by teatree1212** [comment]
For plant trial submission to Zenodo, base the .csv file on the .csv in the 2.5 submission step and add  PlantTrial table information to it. Hopefully the 2.5 step is quickly resolved after #488.

**Comment by teatree1212** [comment]
I have updated the BIP email adresse for the Zenodo account. It is now changed from tgac.ac.uk to  earlham.ac.uk

**Comment by teatree1212** [comment]
Add the plant varieties to the PlantTrial list. basically, the template we let the user design and submit is a good way. 

In addition to that, certain metadata is required: I sent you an email (Monday, 18 July 2016 at 10:22) about a DOI template I made for the upcoming submissions, where I researched the required fields for metadata for a DOI submission. As Zenodo and CyVerse use both the DataCite standards, it should be similar. Can you  give me information on how far you have come with this development and whether you need anything from me still?

**Comment by Nuanda** [comment]
Plant Varieties (or Plant Lines) will be published in the Plant Accessions CSV.

About the metadata (see https://zenodo.org/dev#restapi-rep for Zenodo Deposition Metadata list):
 - title, description, creator, publisher, resourceType, DOI, rights - OK
 - publication year is publication date in Zenodo
 - subjects are taxonomy-based in Zenodo, can you try to find one for me? it does not need to be from http://id.loc.gov/authorities/subjects/ - some other URL-based vocabulary should do (otherwise we can use Zenodo's keywords free text for that)
 - creatorAffiliation is currently not available in BIP (ORCiD does not give us that)
 - contributorName not available at the moment.

**Comment by teatree1212** [comment]
I m on it

**Comment by teatree1212** [comment]
This is focusing on measurements, not image data:

- please see the file attached: field you adressed that were not OK are marked in Yellow. anothe field I adressed is marked in red. all things that you marked as OK, I have coloured green in the sheet. some are grey, as I could not find them to map against anything in Zenodo/as they were marked as required=FALSE were not as important to talk about.

- I added subjects in the comments section. in the Mapped to BIP tables I suggested setting some words as default. I have tried to be as close to these words as possible when finding url-based terms.  If free text is possible, using the content of J6 would be better, otherwise set the 4 terms in J7 as default.

- creatorAffiliation: yes, needs to be made compulsory ( see comments (D7). also trial description should be made compulsory ( see M7)- issue #589.

- contributors: even though not compulsory, we have a long list of names here for the submission of the data in August. Is it possible to connect the "plant_trials.data_provenance" field with their "contributors" field so that they can be named ( default contributor_type "researcher") 
           and in the future we can fully recycle the data_provenance column for such submissions?
[Zenodo_Cyverse_BIP_mapping-discussion.xlsx](https://github.com/TGAC/brassica/files/390551/Zenodo_Cyverse_BIP_mapping-discussion.xlsx)

**Comment by Nuanda** [comment]
Re. `contributors` there will be a text area provided to put names in line-by-line fashion. No more preprocessing though - only names (we'll mark them as `Researchers` in Zenodo). So no need to forcefully reuse `data_provenance` column there.

Re. `affiliation` and `description` - as you suggest. Also the description could be extended with additional content when depositing in Zenodo.

Re. subjects - yes, Zenodo requires them to be URLs. I will set J7 as "Subjects" and put J6 in "keywords".

**Comment by teatree1212** [comment]
contributors: okay, great

affiliation and description: okay. Question: with your "also..." sentence- do you mean you add a feature that the person is asked to fill out additional fields when clicking "request DOI" (to zenodo)?

subjects: understood. Okay.

**Comment by Nuanda** [comment]
Yes - the user is able to alter the Name and the Description, and add the list of Contributors.

**Comment by teatree1212** [comment]
okay, great solution!

**Comment by Nuanda** [comment]
The current prototype preview:

![mbb_screenshot1](https://cloud.githubusercontent.com/assets/107565/17249716/8f967d3c-55a1-11e6-8a56-5f8a03e126a0.png)

**Comment by teatree1212** [comment]
can I suggest some edits:

the idea is that the user doesn't actually notice that this is all happening via a third party service.

call the header ( above the green line): 

"request DOI for dataset <XYZ>"
 in the first blue box:
 - let me think about the blue boxes a bit more.. - but for the rest see below:

beneath the title field:  
"e.g: a name by with the dataset is known. it can be the plant trial name you submitted to BIP or it can be the title of your upcoming publication where you want to cite this dataset in."

Description: 

- is it possible to display what people have entered in the trial_description column earlier and ask something like: "Enter a description of the dataset and how to use it. Currently displayed is your trial_description you submitted earlier in conjunction with the dataset. You can build you DOI-dataset description on this description"

Otherwise: I would't bother with the Description part and recycle the trial_description part.

Contributors:
just be aware that Zenodo asks for the names in this pattern: 
![screen shot 2016-07-29 at 14 41 45](https://cloud.githubusercontent.com/assets/17452217/17250075/a86fd378-559a-11e6-83ca-7095d131e4fe.png)
Therefore maybe write something like: "Please provide a list of contributing researchers that helped generating this dataset. list each name in a separate line, in this fashion: _Family name, given name_ "

**Comment by Nuanda** [comment]
Actually, through all these months I had no idea that you want to _hide_ the fact BIP uses Zenodo for deposition. Anyway, this can't be done, since: (1) in case of errors (like for instance some outage of Zenodo) we need to report that back to the user, and (2) assigned DOIs are resolved to Zenodo, so it's immediately obvious to the users we use Zenodo.

Initial values for Title and Description _are_ copied from PlantTrial columns. User is able to leave them as they are or change them.

Zenodo accepts names in another order as well, so no problem there.

Also, some things like contributors or subjects are not visible on the Zenodo deposition page. They are however in the export JSON you can get from Zenodo for each deposition.

**Comment by teatree1212** [comment]
I hear your irritation. I think Wiktors intention is not to confuse people that are nearly at the end of submitting their data to BIP, suddenly their dataset is being  sent away somewhere else on top of it being submitted to the BIP.
- the Scientists are interested in the fact that they get a DOI. not that their dataset is published in Zenodo, this is a side-effect of having a DOI.

first blue box:
"This action will create a permanent Digital Object Identifier (DOI) for proper citation of this submission data (and metadata related to it)". The DOI is assigned through an external service called Zenodo.org. 
One of the criteria for a dataset to receive a DOI is that it remains "stable" after submission. Therefore, the data you submit to receive a DOI will be exported to Zenodo to ensure that it remains as it is presented at the time of DOI request. If you add any content to your dataset in the BIP after requesting a DOI,but want that information to be part of the stable data for your publication, you need to request a new identifier through this action. It means that the altered dataset and metadata will receive a new DOI. Therefore, please prepare this submission carefully.
We would like to remind you that you are responsible for the contents and specifications of your dataset."

second  blue box:
sounds good, maybe alter  the   last bit:
.."which you would like to publish along with this dataset when requesting a permanent DOI from Zenodo."



Zenodo and other cross-linked facilities like NCBI and in the future CyVerse for Image submission and analysis tools will need to somehow be displayed on the front page ( which also looks great, fianlly BIP is "integrated") - I will think about that.

**Comment by teatree1212** [comment]
green button in the bottom right corner: "request a DOI" rather than "create a deposition"

**Comment by teatree1212** [comment]
How long does it take until one gets a DOI? This should probably also be mentioned somewhere for the user: You said something about 1 week, but that has something to do with BIP, correct? I know that in Cyverse, data is manually curated before it gets assigned a DOI. And that takes a while.

**Comment by Nuanda** [comment]
@teatree1212 Let's not confuse submission to BIP with deposition in Zenodo. This is how these two things work/will work:
 
1. User a new submission in BIP (e.g. a Plant Trial submission) and provides data through the multi-step wizard.
1. User submits the submission to BIP (thus finishing the wizard) and decides, if the submission goes immediately public (for BIP users) or not.
1. If not public, the user can publish that submission later.
1. During 1 week after publication, BIP allows the user to delete the data, or hide it as private again (the revocability period).
1. Afterwards, the data cannot be deleted, made private or altered. Now, as the data is _stable_, we allow the user to deposit it in Zenodo.
1. The deposition in Zenodo is set as public right away and the DOI number is being returned immediately (no delay).

I am not sure how the production Zenodo server works, but I think the published deposition is not shown in the Zenodo front page right away. So I think they reserve some time for review/curation, but the DOI is assigned right away.

**Comment by Nuanda** [comment]
Not as irritated as rather surprised. I think services like BIP might actually like to _stress_ that they are integrated with a thing like Zenodo, and that user's data can be "one-(or two-)clicks published" there, that the submission is therefore backed up twice that way, that people who don't know about BIP might see their submission in Zenodo etc. etc.

Anyway, changing "Deposit in Zenodo" to "Request a DOI" is not what I find difficult. It's the idea to make "the user doesn't actually notice that this is all happening via a third party service". This is simply not possible (it's instantly obvious anyway that it happened through Zenodo - it's enough to click on the assigned DOI number) and, perhaps, also even not _fair_ to the user, who might want to know that her/his data is going to be sent _somewhere else_ (outside BIP).

Since you (as I understand it) have later proposed to keep the information that we, in fact, use Zenodo, I have no objection to this change.

**Comment by teatree1212** [comment]
okay, thanks for this.

**Comment by teatree1212** [comment]
about your second comment, I agree. It is better to keep the user informed. But it is also important to stress that this doesn't come with additional work for them but is an automatised submission performed by BIP.
