### ISSUE TITLE
prepare materials and methods section

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#498]
For the paper, please have a look at the materials and methods section. It so far includes a brainstorming list of things that may need to be mentioned.i also compied and pasted an example from a different paper in this section so you can see how it can be done. It doesn't need to be long or fancy but just descriptive. Sometimes it would be good to say why you chose one thing over other possibilities.
I will send the link to the googleDoc via email.

**Comment by Nuanda** [comment]
I have just provided the text, together with two figures (appended in the end of the document, like the other figures). I apologize for my grammar mistakes, please try to correct the language (particularly, since I'm Polish, probably most of the articles are not correct ;)).

If I should provide more material, please tell me.

**Comment by teatree1212** [comment]
thanks! I will do so once you are happy with your text. I see you are still moving things around.

**Comment by Nuanda** [comment]
Please go ahead and review the text. I have also rewritten the part of your text regarding the trial submission - I tried to update it. Please see that part too (I made a comment so you know which part was changed),
