### ISSUE TITLE
trait_descriptor_id and descriptor_names

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#556]
Hi, not sure whether I am just not getting it but:
When doing 
SELECT Trait_Scores.id,Trait_Scores.trait_descriptor_id, Trait_Scores.score_value, Trait_Scores.value_type, Trait_Descriptors.descriptor_label,Trait_Descriptors.descriptor_name  FROM Trait_Scores, Trait_Descriptors WHERE Trait_Scores.trait_descriptor_id='12';

I get this:
<img width="872" alt="screen shot 2016-06-17 at 15 11 25" src="https://cloud.githubusercontent.com/assets/17452217/16153361/eab5592e-349d-11e6-8481-2f1ae8f46ef5.png">

So rather than being assigned to the descriptor_name, the trait_descriptor_id seemds to be assigned to the score_value, in a similar manner the Trait_Scores.id is...?
I dont' think this is right. 

I came across this when trying to come up with a trait_descriptor_id for an API query. 

https://bip.tgac.ac.uk/api/v1/trait_scores?trait_score[query][trait_descriptor_id]=12

What is important for the researcher is that s/he can obtain trait_values from the Trait_Scores table  of the same trait (trait_names) , for comparison between them ( as they may have been derived from different trials.)

And when using the API, this is actually a very hidden and more problematic issue: The user has to rely on the trait_descriptor_id to get all values related to the - what s/he thinks is the trait erucic acid content.

SO
> the relation should be checked 
> and then then somehow the content of fields of related tables which at the moment are IDs should get maybe shown to the user for queries.

Or can I query with the name? I tried this too and in fact didn't receive an error message, but  didn't get any output either. and I know from the SQL query above, that there must be at least one value associated with that trait ( 43.48).
<img width="726" alt="screen shot 2016-06-17 at 15 18 57" src="https://cloud.githubusercontent.com/assets/17452217/16153585/d9ec6a5a-349e-11e6-887a-b635c9598e09.png">

**Comment by Nuanda** [comment]
@teatree1212 Annemarie, I think you miss the actual JOIN in your query. The way you construct your query you are getting the full Cartesian product (the chosen TD(12) multiplied for all scores). Please change your FROM part to the following:
```
FROM Trait_Scores JOIN trait_descriptors ON trait_scores.trait_descriptor_id = trait_descriptors.id
```

Is this what you wanted to get?

**Comment by teatree1212** [comment]
oopsi, yes. (:

**Comment by teatree1212** [comment]
cheers !

**Comment by teatree1212** [comment]
about the second question- can I use the actual trait name to perform the search ( I know it is from a different table)? Or is it possible - somehow and I have no idea how to do it.. maybe with a little API-query "id-search engine" .. to make it easier for the people to know what they need to query for?

**Comment by Nuanda** [comment]
I assume the task is: 'Get all scores from BIP which are related with a given trait T' (for instance, where T equals _erucic acid content_. One can achieve it in several ways.

**Browser**
Go to https://bip.tgac.ac.uk/data_tables?group=true&model=trait_descriptors, find the trait T in question, click 'Related -> X trait scores' and the table with all scores for this trait appears (then, e.g., 'Export to CSV'). To speed things up one can:
 - use 'Search' in the first table to quickly locate _erucic acid content_ (yes, there are 3 such traits in BIP now, but this is another issue, if you can call it that: #503)
 - even faster, use the front page 'Search for...' field, type in 'erucic', hit enter and click 'Found 3 trait descriptors'.

**API**
Using API you proceed exactly as you did. It is, arguably, a longer procedure, but since API is for programmatic use (e.g. through scripting) I think this is more or less what should be expected. If you are not sure what is the ID of the trait descriptor you are looking for, you can either get all of them and check (this is, I guess, what you did), or you can use the 'Search' capability (https://bip.tgac.ac.uk/api_documentation#searching-for-data):

```
curl -g -X GET "https://bip.tgac.ac.uk/api/v1/trait_descriptors?trait_descriptor[fetch]=erucic" -H "X-BIP-Api-Key: YOUR_API_KEY"  -H "Content-Type: application/json"
```

and you get the three hits, in JSON format. Having the `trait_score_ids` array right there helps you judge which trait descriptor is the one you are looking for.

**Comment by Nuanda** [comment]
Regarding the third part, that is, API-querying trait scores by trait name, you can't do that with the `query` parameter. You could, however, do that with the `fetch` parameter (as in my `curl` example above, only for `trait_scores` table).

You _could_, as with latest model changes (namely, introduction of the new `traits` vocabulary table), you can't do that at the moment. Issue #515 is there to remind us to adjust these search indices when we are finished with major model changes.

**Comment by Nuanda** [comment]
Can we close this one?

**Comment by teatree1212** [comment]
yes
