### ISSUE TITLE
API TraitDescriptor Submission

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#574]
@Nuanda 
With my limited knowledge, the API documentation does not help me enough to submit the following trait description data to the database 

[Trait_Defs_APIsubmission.xlsx](https://github.com/TGAC/brassica/files/350240/Trait_Defs_APIsubmission.xlsx)
[Table_Trait_APIsubmission.xlsx](https://github.com/TGAC/brassica/files/350241/Table_Trait_APIsubmission.xlsx)

I have tried to find them in the tables of the database and identified two tables "trait" and "Trait_descriptor" to host these fields. How do I submit the data to two different tables using the API?
I have a feeling that I have to submit content to one table first (trait.) and then to the other( Trait_desciptor.) and somehow make their connection clear with the identifier of the first. ( see json files:

[Trait_descriptor_rootData.txt](https://github.com/TGAC/brassica/files/350268/Trait_descriptor_rootData.txt)
[Trait_rootData.txt](https://github.com/TGAC/brassica/files/350267/Trait_rootData.txt)

Or can I do something like this format and the API is able to post it accordingly?

{
"trait_descriptor":  {
    "category": "Morphological",
    "stage_scored": "seedling stage",
    "scoring_method": "RootReader2D (RR2D, Clark et al., 2013) was used to analyse images. First, a  was carried out which automatically 'thresholds', 'skeletonises' and 'builds segments' of all images in bulk. Then, the the root system of individual images was measured by placing a marker at the base and tip of the primary root. From these markers, RR2D automatically calculates primary root length (PRL), lateral root length(LRL) of all laterals and lateral root number (LRN).",
    "units_of_measurements": "cm",
   "trait": {
    "data_provenance": "Catherine Thomas, Nottingham",
    "description": "Length of the primary root",
    "name": "Primary root length" }
      }
 }

Also, I noticed that there are no "POST" instructions for the Traits table, which probably corresponds to the missing feature of submitting trait names yourself in the wizard. 
If I suspect correctly, please add this feature asap because :
This exercise will need to be performed several times in the near future.
so if you could walk me through, I will do it myself afterwards.

**Comment by teatree1212** [comment]
This goes in conjunction with the submission of the first trait data to the BIP, on the 7th of August. let's please get this solved at least 2 weeks before that.

**Comment by kammerer** [comment]
@teatree1212 You are correct that it is not currently possible to submit Traits via API. It is also correct that your submission would require posting Traits first (if that was possible), keeping track of returned ids and then posting TraitDescriptors with proper Trait ids included.

**Comment by Nuanda** [comment]
Do you think the `description` for a new Trait should be required as well?

**Comment by teatree1212** [comment]
yes

**Comment by teatree1212** [comment]
If you are working on this now, shall I still send you the traits for you to upload? ( thinking of issue #573)

**Comment by Nuanda** [comment]
Yes, please send them. Actually this is not totally straightforward and it will take some time.

**Comment by teatree1212** [comment]
email with trait descriptors sent. Subject "trait descriptors BIP for #573/#574". This request is also part of #573 .

**Comment by Nuanda** [comment]
Some Traits are already there, like e.g. 'lateral root length', so I will re-use them instead of duplicating the entry in the vocabulary.

Also, I have loaded terms like 'Seed Cu', following your list in the google docs. I assume this term is the same as 'The concentration of Copper in seeds' and should be reused, rather than duplicated?

**Comment by Nuanda** [comment]
A copy of Annemarie's answer made in another issue:

First: These fields you are going to upload are part of a much bigger table that is going to be submitted to CO. In the future, these will be the most valuable trait descriptors for our database ( along with the old CropStore trait descriptors) as they are especially made up for describing traits in Brassica. Please consider Trait Ontolgy as the best intermediate solution until we switch to Crop Ontology.

1) I also noticed that some traits can be found in trait ontology. However, as we will in the future cross-link with Crop Ontology rather than trait ontology, please use "my" description for now, as this will be exactly what people will find once we include CO terms.

2)yes, many of these and in the future to be submitted Trait descriptors are revised ( following the CO model) trait descriptors I already gave to you. Please treat them the same way as TO terms in 1) and prioritise this sheet as the most correct and up to date content.
