### ISSUE TITLE
delete test trial submissions

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#585]
I thought you deleted current test submissions. 
However, I can still see content related to trials and populations ( but not the scores themselves) when looking up "ASSYST". 
I recently submitted "ASSYST accessions" which, of course also come up. Could you remove any entry that has "ASSYST" in their fields which are searchable via the website's search field?

**Comment by Nuanda** [comment]
Related to #486

**Comment by Nuanda** [comment]
@nowakowski Piotr, please perform the data clean on the production server. Do not forget to make the data backup prior to doing that.

Two approaches are possible:
 - either, bootstrapping the DB with the app:bootstrap task from scratch
 - or removing all Submissions, all Submission Uploads and all records from other tables which have `user_id` not set to nil.

The second approach is a bit more user friendly since you do not invalidate current API Keys (preferred).
