### ISSUE TITLE
Load new TDs provided by Annemarie

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#587]

**Comment by teatree1212** [comment]
to answer your questions in #574 
1) "Some Traits are already there, like e.g. 'lateral root length', so I will re-use them instead of duplicating the entry in the vocabulary."

2) "Also, I have loaded terms like 'Seed Cu', following your list in the google docs. I assume this term is the same as 'The concentration of Copper in seeds' and should be reused, rather than duplicated?"

First: These fields you are going to upload are part of a much bigger table that is going to be submitted to CO. In the future, these will be the most valuable trait descriptors for our database ( along with the old CropStore trait descriptors) as they are especially made up for describing traits in Brassica. Please consider Trait Ontolgy as the best intermediate solution until we switch to Crop Ontology.

1) I also noticed that some traits can be found in trait ontology. However, as we will in the future cross-link with Crop Ontology rather than trait ontology, please use "my" description for now, as this will be exactly what people will find once we include CO terms.

2)yes, many of these and in the future to be submitted Trait descriptors are revised ( following the CO model) trait descriptors I already gave to you. Please treat them the same way as TO terms in 1) and prioritise this sheet as the most correct and up to date content.
