### ISSUE TITLE
Add PL <-> PA, PV <-> PA and PL -> TS navigation possibility to data tables

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#648]

**Comment by teatree1212** [comment]
Importance of this feature also relevant for users arriving at BIP through cross-linking with TGAC-browser.  mentioned in email Thursday, 8 September 2016 at 11:36

**Comment by Nuanda** [comment]
I see. I added the new PL -> TS navigation option.

**Comment by kammerer** [comment]
@wjurkowski Should the PV <-> PA link take into account directly related records or should it include records related via PL? I assume the latter, otherwise the table would appear to be inconsistent.

However, the PL <-> PA link should show only directly related PA records (because PV consists of many PLs), correct?

**Comment by wjurkowski** [comment]
Yes, to both questions!
