### ISSUE TITLE
Strange new plant line list "memory" during the PP submission

### ISSUE THREAD

**Issue by Nuanda** [TGAC/brassica#698]
To reproduce (a bit tricky):
 - have a PP submission on step03 with a new plant line in the Plant Line List input
 - delete it with the "x" icon and click NEXT, BACK, to make sure this is saved
 - the input list should be empty
 - upload a plant line CSV file with some other plant line definition
 - the Plant Line List input should be populated with the new line from the uploaded file _but also_ with the new plant line that was there previously, and should be gone by now.

Please verify, since I'm not 100% sure I am not mistaken about that.

**Comment by kammerer** [comment]
You are right, it works like you described. Server-side content is not updated when you remove PL from the list input, so when you append new PLs via CSV upload both existing and appended PLs are added to input.
I have an idea how to fix it, but I probably won't be able to do that today.

**Comment by Nuanda** [comment]
I understand. Just give priority to this one.

**Comment by kammerer** [comment]
@Nuanda It is not so simple after all. I can fix it easily only if I allow users to overwrite existing PLs by removing [this check](https://github.com/TGAC/brassica/blob/master/app/services/submission/plant_line_parser.rb#L97). That is because the parser cannot know what PLs were removed from the input.

The other way would be to return the log the client in such a way that it would be possible to skip the message and silently append removed PL to the input.

Generally speaking, the situation in which submission content is updated by file upload is unfortunate.

**Comment by Nuanda** [comment]
@kammerer I realised we might be talking about different things. As you click NEXT/BACK buttons, the PL list _should_ be persisted in the form content object, hence this is not the effect which you refer to. Can you check if you are able to recreate this bug exactly the way I described it?

**Comment by Nuanda** [comment]
I have tested it again and I know the cause - when you click NEXT after you have removed a _new_ PL from the Plant Lines List, the new PL data still stays in the `new_plant_lines` server-side content attribute (it is removed from the `plant_line_list` attribute, as expected). This in itself is probably harmless.

Yet, when you go BACK and you try to upload any file, even if it successfully parses 0 new plant lines, the previous new PL will be (this is my guess) copied from `new_plant_lines` into `plant_line_list` like it _was_ just parsed.

Would the solution be to update also the `new_plant_lines` attribute when you click SAVE or NEXT?

**Comment by kammerer** [comment]
All right, we were talking about a bit different things. I will create a PR with fix shortly.
