### ISSUE TITLE
does GWASSER misinterpret read-ins?

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#721]
submission
repeat_harper_et_al_2012:

 unfortunately......
there are certain names like "Moana, Moana Rape", which can be misinterpreted when reading into GWASSER, because they themselves have a "," in the name ( this gave me SO much grief..).

This is also a problem in the population submission i would think. I wonder whether we should require people to submit for example Cultivar names like this " Culti,var,Name".

This was why I thought my first submission (repeat_harper_et_al_2012) crashed. 

submission
repeat_harper_et_al_2012b
so I re-named this "sample"  to Moana_Moana_Rape in both files, but still got a message that something went wrong.

Let me know what i can do.

**Comment by wjurkowski** [comment]
I would lean towards allowing use only line IDs or accessions as sample identifiers. Use of cultivar names is problematic also due to the fact of multiple accessions representing given cultivar.

**Comment by teatree1212** [comment]
I know, but in the Harper case they compare on this kind of level. They give you the Cultivar names and some Sequence Library Names for one individual from that cultivar that has been used in the Sequencing and variant calling.

**Comment by kammerer** [comment]
@teatree1212 It should be possible to use commas inside names but in that case the CSV must be quoted. Otherwise the file would not make sense as part of the name would be interpreted as next value in sequence.
However, it looks that it is the pheno-file that has issues which prevented you from creating the analysis.
I will have to think how to better communicate requirements for these files and detect issues with them.

**Comment by teatree1212** [comment]
I found the mistakes and solved them. The analysis is now successfully submitted. Let’s see what happens.

**Comment by teatree1212** [comment]
Any news? I send files and the Rscript via email last week.

**Comment by kammerer** [comment]
@teatree1212 It seems that GWASSER fails on the input files taken from analysis named "repeat_harper_et_al_2012c_again". I have not identified the reason for that yet.

**Comment by kammerer** [comment]
@teatree1212 I found that GWASSER fails because there are some SNPs in geno data that only have one distinct value (NA does not count).

There are also some less important issues:

- GWASSER changes ids of samples/snps/traits if they include some special characters
- Manhattan plot does not handle such big datasets well enough

When I removed problematic SNPs and normalized ids I was able to run analysis directly with GWASSER as well as using BIP. 

Manhattan plot generated by GWASSER is [here](https://drive.google.com/file/d/0BzlTet3SNRNTZHNYdU9pUWFYNE0/view?usp=sharing).

I will now make BIP remove irrelevant SNPs from the data files automatically (and fix remaining issues as well).

**Comment by wjurkowski** [comment]
Sounds great! Thanks @kammerer !

**Comment by teatree1212** [comment]
I have replaced the NAs with 0s ( which I think is not actually adequate for the analysis , but jsut to see whether it works)
I have removed the letters in the position file

but it is still not working when submitting through BIP.

what special characters do I have to watch out for?

**Comment by kammerer** [comment]
@teatree1212 It seems that the map file has inconsistent line-breaks and it trips the CSV parser. Every line except the last one ends with CRLF, but the last one does not. I missed this one, but it is an easy fix.

Using zeros instead of NA may not work if there were SNPs with only NAs and zeros. My approach is to remove these SNPs altogether.

**Comment by kammerer** [comment]
@teatree1212 @wjurkowski I deployed code from a branch which includes several improvements to GWAS, mainly better handling of input files (i.e. fixes for issues mentioned above) and optimization of results view. I run analysis using the same data as last @teatree1212's analysis and it succeeded (took ~3h). This code is not yet reviewed by @Nuanda, but I do not expect much changes in functionality.

**Comment by kammerer** [comment]
Should be fixed by #725
