### ISSUE TITLE
hapmap testing 'ID'/ csv error

### ISSUE THREAD

**Issue by teatree1212** [TGAC/brassica#743]
I was just trying out the new hapmap input format. But get the following error:
No 'ID' column found in genotype CSV file.
But since I do not submit a CSV file, and a hapmap format does not require an "id", I don't know what to do about this..

I will send you the files I am working with.

**Comment by kammerer** [comment]
May I ask what is the source of this file? As HapMap is not a common file format I am guessing the type by looking at the file header. The problem is that its header looks a bit different than every file in this format I managed to find on the web. The first column is supposed to be "rs#" not "rs". If this is normal to have just "rs" as first column then I will update the logic that checks it. Also, to avoid confusion I am going to show the file type that was recognized recognized.

**Comment by wjurkowski** [comment]
I would suggest to stick to the original HapMap format. I updated the header to match the example in: http://augustogarcia.me/statgen-esalq/Hapmap-and-VCF-formats-and-its-integration-with-onemap/#hapmap

Now I get the following error:

translation missing: en.activerecord.errors.models.analysis.attributes.genotype_data_file.not_a_hapmap

**Comment by kammerer** [comment]
I changed first columns of the header to the following and it was accepted:
```
rs# alleles chrom pos strand assembly# center protLSID assayLSID panelLSID QCcode
```

I also needed to change "Apex-93_5_X_Ginyou_3 line" in pheno file to "Apex-93_5_X_Ginyou_3_line" to match geno file.

However, this file still looks wrong as the "alleles" column only contains `NA` values.

**Comment by kammerer** [comment]
To be clear - I do not expect "NA" in alleles at all.

**Comment by kammerer** [comment]
The files used here did not adhere to specified input format. After examining this issue we identified several possible improvements described in #752.
